network:
  version: 2
  renderer: networkd
  ethernets:
    ens6:
      addresses:
       - subnet
      dhcp4: no
      routes:
       - to: 0.0.0.0/0
         via: gateway # Default gateway
         table: 1000
       - to: ip
         via: 0.0.0.0
         scope: link
         table: 1000
      routing-policy:
       - from: ip
         table: 1000
